### ISSUE TITLE
OPN-2001 Fedora 21

### ISSUE THREAD

**Issue by ghost** [fazalmajid/cs1504#5]
Hello, I'm running OPN-2001 under Fedora 21 with your python script.

My problem:

```
[root@ cs1504]# python cs1504.py 
Traceback (most recent call last):
  File "cs1504.py", line 322, in <module>
    scanner = CS1504(serial_port)
  File "cs1504.py", line 135, in __init__
    timeout=2)
  File "/usr/lib/python2.7/site-packages/serial/serialutil.py", line 261, in __init__
    self.open()
  File "/usr/lib/python2.7/site-packages/serial/serialposix.py", line 281, in open
    self._reconfigurePort()
  File "/usr/lib/python2.7/site-packages/serial/serialposix.py", line 412, in _reconfigurePort
    termios.tcsetattr(self.fd, TERMIOS.TCSANOW, [iflag, oflag, cflag, lflag, ispeed, ospeed, cc])
termios.error: (22, 'Invalid argument')
Exception AttributeError: "CS1504 instance has no attribute 'ser'" in <bound method CS1504.__del__ of <__main__.CS1504 instance at 0x7f965d5bcc68>> ignored

[root@ cs1504]# lsusb
Bus 002 Device 002: ID 8087:0024 Intel Corp. Integrated Rate Matching Hub
Bus 002 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub
Bus 001 Device 005: ID 5986:0299 Acer, Inc 
Bus 001 Device 004: ID 8087:07da Intel Corp. 
Bus 001 Device 003: ID 09da:9090 A4Tech Co., Ltd. XL-730K / XL-750BK / XL-755BK Mice
Bus 001 Device 002: ID 8087:0024 Intel Corp. Integrated Rate Matching Hub
Bus 001 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub
Bus 004 Device 001: ID 1d6b:0003 Linux Foundation 3.0 root hub
Bus 003 Device 004: ID 065a:0009 Optoelectronics Co., Ltd NLV-1001 (serial mode) / OPN-2001 [Opticon]
Bus 003 Device 002: ID 045e:00db Microsoft Corp. Natural Ergonomic Keyboard 4000 V1.0
Bus 003 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub

```

**Comment by brendankehoe** [comment]
Comment on another issue applies here: https://github.com/fazalmajid/cs1504/issues/4#issuecomment-267823965
